# Generated by Django 5.1.4 on 2024-12-14 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_issue_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='in_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL),
        ),
    ]
